# Generated by Django 4.1 on 2022-08-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_emaillist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailList',
        ),
    ]
