# Generated by Django 4.1 on 2022-08-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='body',
            field=models.TextField(),
        ),
    ]
